# Generated by Django 5.0.6 on 2026-04-17 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AlterModelOptions(
            name='appointments',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='appointmentstatus',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bills',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='medicalrecords',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='medicines',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='medicinestock',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='owners',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='petallergies',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pets',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='posbills',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='treatments',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vaccinations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='veterinarians',
            options={'managed': True},
        ),
    ]
