# Generated by Django 5.0.6 on 2026-04-17 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_staff_alter_appointments_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE Users DROP COLUMN staff_id;",
            reverse_sql="ALTER TABLE Users ADD COLUMN staff_id VARCHAR(6);",
        ),
    ]
