# Generated by Django 5.0.6 on 2026-04-17 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_drop_users_staff_column'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS Staff;",
            reverse_sql="CREATE TABLE Staff (staff_id VARCHAR(6) PRIMARY KEY, staff_name VARCHAR(100) NOT NULL, position VARCHAR(50), phone VARCHAR(15));",
        ),
    ]
