# Generated by Django 5.0.6 on 2026-04-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_drop_staff_table'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS Pet_Allergies;",
            reverse_sql="",
        ),
    ]
