# Generated by Django 5.0.6 on 2026-04-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_pet_allergies'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS Vaccinations;",
            reverse_sql="",
        ),
    ]
